### ISSUE TITLE
axblack applies some weird wrapping compared to normal black

### ISSUE THREAD

**Issue by ThiefMaster** [axiros/axblack#7]
See the diff below. This happened when running axblack on the [newdle codebase](https://github.com/indico/newdle/). The code was previously formatted using standard `black==20.8b1` (with quote normalization disabled of course). The unwrapping by itself wouldn't be a problem, but the `,)` it causes by doign so are incredibly ugly :/

```diff
diff --git a/conftest.py b/conftest.py
index d46dea5..2ad83cb 100644
--- a/conftest.py
+++ b/conftest.py
@@ -118,11 +118,7 @@ def create_newdle(dummy_uid, db_session):
         kwargs.setdefault('duration', timedelta(minutes=60))
         kwargs.setdefault('private', True)
         kwargs.setdefault('timezone', 'Europe/Zurich')
-        newdle = Newdle(
-            id=id,
-            creator_uid=dummy_uid,
-            **kwargs,
-        )
+        newdle = Newdle(id=id, creator_uid=dummy_uid, **kwargs,)
         db_session.add(newdle)
         db_session.flush()
         return newdle
diff --git a/newdle/core/util.py b/newdle/core/util.py
index 0ae3d74..a1a3f47 100644
--- a/newdle/core/util.py
+++ b/newdle/core/util.py
@@ -108,20 +108,14 @@ def render_user_avatar(initial, size):
 
 def avatar_payload_from_user_info(user_info):
     return secure_serializer.dumps(
-        {
-            'email': user_info['email'],
-            'initial': user_info['first_name'][0].upper(),
-        },
+        {'email': user_info['email'], 'initial': user_info['first_name'][0].upper(),},
         salt='avatar-payload',
     )
 
 
 def avatar_payload_from_participant(participant):
     return secure_serializer.dumps(
-        {
-            'email': participant.email,
-            'initial': participant.name[0].upper(),
-        },
+        {'email': participant.email, 'initial': participant.name[0].upper(),},
         salt='avatar-payload',
     )
 
diff --git a/newdle/migrations/versions/20200814_1707_93a638b96375_add_private_column_to_newdle_model.py b/newdle/migrations/versions/20200814_1707_93a638b96375_add_private_column_to_newdle_model.py
index 9491dd5..f12a806 100644
--- a/newdle/migrations/versions/20200814_1707_93a638b96375_add_private_column_to_newdle_model.py
+++ b/newdle/migrations/versions/20200814_1707_93a638b96375_add_private_column_to_newdle_model.py
@@ -22,9 +22,7 @@ def upgrade():
         sa.Column('private', sa.Boolean(), nullable=False, server_default='true'),
     )
     op.alter_column(
-        'newdles',
-        'private',
-        server_default='false',
+        'newdles', 'private', server_default='false',
     )
 
 
diff --git a/newdle/migrations/versions/20200922_1759_43f0bf77bf97_add_newdle_creator_email_notify.py b/newdle/migrations/versions/20200922_1759_43f0bf77bf97_add_newdle_creator_email_notify.py
index f83e33b..c23ef87 100644
--- a/newdle/migrations/versions/20200922_1759_43f0bf77bf97_add_newdle_creator_email_notify.py
+++ b/newdle/migrations/versions/20200922_1759_43f0bf77bf97_add_newdle_creator_email_notify.py
@@ -26,9 +26,7 @@ def upgrade():
         sa.Column('notify', sa.Boolean(), server_default='false', nullable=False),
     )
     op.alter_column(
-        'newdles',
-        'notify',
-        server_default='true',
+        'newdles', 'notify', server_default='true',
     )
 
 
diff --git a/newdle/vendor/django_mail/backends/smtp.py b/newdle/vendor/django_mail/backends/smtp.py
index e7c99ad..caad7c5 100644
--- a/newdle/vendor/django_mail/backends/smtp.py
+++ b/newdle/vendor/django_mail/backends/smtp.py
@@ -59,8 +59,8 @@ class EmailBackend(BaseEmailBackend):
         self.ssl_certfile = ssl_certfile
         if self.use_ssl and self.use_tls:
             raise ValueError(
-                "EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set "
-                "one of those settings to True."
+                'EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set '
+                'one of those settings to True.'
             )
         self.connection = None
         self._lock = threading.RLock()
diff --git a/tests/api_test.py b/tests/api_test.py
index 84a77ba..d55298d 100644
--- a/tests/api_test.py
+++ b/tests/api_test.py
@@ -22,11 +22,7 @@ def add_avatar(participant_data):
     )
     return {
         **participant_data,
-        'avatar_url': url_for(
-            'api.user_avatar',
-            payload=payload,
-            _external=False,
-        ),
+        'avatar_url': url_for('api.user_avatar', payload=payload, _external=False,),
     }
 
 
@@ -929,13 +925,7 @@ def test_create_unknown_participant(flask_client):
     id_ = data.pop('id')
     participant = Participant.query.filter_by(name=name).first()
     assert data == add_avatar(
-        {
-            'answers': {},
-            'auth_uid': None,
-            'email': None,
-            'name': name,
-            'comment': '',
-        }
+        {'answers': {}, 'auth_uid': None, 'email': None, 'name': name, 'comment': '',}
     )
     newdle = Newdle.query.filter_by(code='dummy').first()
     assert Participant.query.count() == num_participants + 1
@@ -1043,8 +1033,7 @@ def test_send_result_emails(flask_client, dummy_newdle, mail_queue, dummy_uid):
     assert len(mail_queue) == 0
     dummy_newdle.final_dt = datetime(2019, 9, 12, 13, 30)
     resp = flask_client.post(
-        url_for('api.send_result_emails', code='dummy'),
-        **make_test_auth(dummy_uid),
+        url_for('api.send_result_emails', code='dummy'), **make_test_auth(dummy_uid),
     )
     assert len(mail_queue) == 1
     assert resp.status_code == 204
@@ -1053,8 +1042,7 @@ def test_send_result_emails(flask_client, dummy_newdle, mail_queue, dummy_uid):
 @pytest.mark.usefixtures('dummy_newdle')
 def test_send_result_emails_forbidden(flask_client):
     resp = flask_client.post(
-        url_for('api.send_result_emails', code='dummy'),
-        **make_test_auth('wrong_user'),
+        url_for('api.send_result_emails', code='dummy'), **make_test_auth('wrong_user'),
     )
     assert resp.status_code == 403
 
@@ -1072,8 +1060,7 @@ def test_send_result_emails_404(flask_client, dummy_uid):
 def test_send_deletion_emails(flask_client, dummy_newdle, mail_queue, dummy_uid):
     assert len(mail_queue) == 0
     resp = flask_client.post(
-        url_for('api.send_deletion_emails', code='dummy'),
-        **make_test_auth(dummy_uid),
+        url_for('api.send_deletion_emails', code='dummy'), **make_test_auth(dummy_uid),
     )
     assert len(mail_queue) == 1
     assert resp.status_code == 204
diff --git a/tests/notifications_test.py b/tests/notifications_test.py
index 2ab7fb9..a3b09fc 100644
--- a/tests/notifications_test.py
+++ b/tests/notifications_test.py
@@ -44,10 +44,7 @@ def test_replied_email_plaintext(snapshot, update, available, comment, snapshot_
 
 @pytest.mark.parametrize(
     ('comment', 'snapshot_name'),
-    (
-        (False, 'deletion-nocomment.txt'),
-        (True, 'deletion-comment.txt'),
-    ),
+    ((False, 'deletion-nocomment.txt'), (True, 'deletion-comment.txt'),),
 )
 def test_deletion_email_plaintext(snapshot, comment, snapshot_name):
     text = render_template( 
```

**Comment by axgkl** [comment]
A dream comes true: 25 years after my Physics degree I'm finally working for CERN, yay!!
;-)
But.. I don't even understand the question - isn't the formatting exactly ident to PSF's black (except the line length)?

**Comment by ThiefMaster** [comment]
oh, axblack has a different default line length? that'd explain it... even though black keeping those commas is quite ugly

**Comment by ThiefMaster** [comment]
I just tested in a clean virtualenv and there's a difference in formatting behavior:

```python
[adrian@eluvian:/tmp/blacktest]> cat test.py
def foo():
    """Test."""

    foobar = Foobar(
        id=id,
        creator_uid=dummy_uid,
        **kwargs,
    )

    return foobar

[adrian@eluvian:/tmp/blacktest]> ./blackenv/bin/black --version
black, version 20.8b1
[adrian@eluvian:/tmp/blacktest]> ./axblackenv/bin/black --version
black, version 20201012

[adrian@eluvian:/tmp/blacktest]> ./blackenv/bin/black --diff -S test.py
All done! ✨ 🍰 ✨
1 file would be left unchanged.

[adrian@eluvian:/tmp/blacktest]> ./axblackenv/bin/black --diff -S test.py
--- test.py     2020-10-28 16:01:23.209532 +0000
+++ test.py     2020-10-28 16:01:50.995991 +0000
@@ -1,11 +1,7 @@
 def foo():
     """Test."""

-    foobar = Foobar(
-        id=id,
-        creator_uid=dummy_uid,
-        **kwargs,
-    )
+    foobar = Foobar(id=id, creator_uid=dummy_uid, **kwargs,)

     return foobar

reformatted test.py
All done! ✨ 🍰 ✨
1 file reformatted.
```

Default line length is the same (88) in black and axblack anyway, but I tried `-l 88` just in case; same behavior as above.

**Comment by ThiefMaster** [comment]
OK, both `axblack` and `oitnb` have the behavior from `black==19.10b0`; while `black>=20.8b0` changed the logic.

**Comment by ThiefMaster** [comment]
Updating axblack to be based on the latest black codebase is probably the best solution here, but doesn't look particularly pleasant... `3102 insertions(+), 562 deletions(-)` :/

**Comment by Bobronium** [comment]
Would love to see this project up to date with current black version.

Maybe this will help in the future https://github.com/marketplace/actions/fork-sync?

**Comment by axgkl** [comment]
@MrMrRobat  
> Would love to see this project up to date with current black version.
I'd rather love to see them giving up their dictatorship attitude, bypassing any established (PEP) voting process, so that we can ditch this one - but thats a different story :-/

fork-sync looks interesting, will check if it would work, to keep this here in sync with theirs.

@ThiefMaster, @MrMrRobat: 

I'm pretty restricted in time these days but I'm comitted to merging in new features - if they are useful and until fork-sync works.
Question:  
Are there features you miss?

This one:
```
+    foobar = Foobar(id=id, creator_uid=dummy_uid, **kwargs,)
```
with a line len of 88 - that's correct, no?

**Comment by Bobronium** [comment]
> with a line len of 88 - that's correct, no?

It's not correct with any line length because of trailing comma

**Comment by ThiefMaster** [comment]
> It's not correct with any line length because of trailing comma

upstream black has the same bug when it "un-wraps" a statement that had trailing commas before

FWIW, the change wasn't so much a problem by itself, I was just surprised that black-formatted code got reformatted. But this was simply because the latest upstream black release formats this code differently.

tbh, I don't think updating axblack right now is straightforward, because of some major restructuring and refactoring done upstream. I had a look at the diff between the relevant files was over a thousand lines... so it's probably best to just mention in the docs on which black version axblack is based so people don't expect any black features from newer versions...

**Comment by axgkl** [comment]
> > It's not correct with any line length because of trailing comma
> 
Got used to that as well, since they introduced it for datastructures like lists and sets. But I'm with you, on a single line its actually ugly and superflucious. The funny thing: I just tried to see what the official black does and keeps reformatting those things into multiple lines:

<details><summary>See here, pretty vertical....</summary>

```python
(myenv) 1.~$ cat t.py
def foo():
    """Test."""

    foobar = Foobar(
        id=id,
        creator_uid=dummy_uid,
        **kwargs,
    )

    def foo(
        id=id,
        creator_uid=dummy_uid,
        **kwargs,
    ):
        pass

    return foobar
(myenv) 1.~$ black --version
black, version 20.8b1
(myenv) 1.~$ black t.py -l 1000
All done! ✨ 🍰 ✨
1 file left unchanged.
```
unchanged?!


</details>


Is this now the new style or am I doing something wrong?
I'm not sure if I actually want that, would you? Also I'd have to check back with my colleagues

> upstream black has the same bug when it "un-wraps" a statement that had trailing commas before

thanks for that info.

> FWIW, the change wasn't so much a problem by itself, I was just surprised that black-formatted code got reformatted. But this was simply because the latest upstream black release formats this code differently.
> 
> tbh, I don't think updating axblack right now is straightforward, because of some major restructuring and refactoring done upstream. I had a look at the diff between the relevant files was over a thousand lines... so it's probably best to just mention in the docs on which black version axblack is based so people don't expect any black features from newer versions...

Rite. If we would want new stuff I guess merging would not be the way, compared to doing a new fork using fork-sync. The single quotes are actually a tiny diff, especially if we would omit the CLI switch, which nobody needs I guess (for double lovers the official version is anyway the way to go).

**Comment by ThiefMaster** [comment]
> Is this now the new style or am I doing something wrong?

I think black changed it recently (20.x). Not sure what triggers the wrapping there... maybe number of arguments..

**Comment by axgkl** [comment]
@ThiefMaster
> I think black changed it recently (20.x).

I had to fight internally, with authority, for 88 - colleagues wanted 120 default. Cant' imagine anybody keen on such a waste of screen estate.

Let's go with your suggestion and make clear which version the fork is based on - and note such differences.

Once they come up with an actually *convincing* new feature and still keep banning single quotes we might do a new fork (if no other more prominent institution or person (like Raymond Hettinger) does....

Agreed?

**Comment by ThiefMaster** [comment]
> I had to fight internally, with authority, for 88 - colleagues wanted 120 default. Cant' imagine anybody keen on such a waste of screen estate.

I could be one of these colleagues. ;) (with manual formatting having 120 chars max is pretty decent)
But keeping this line length with an autoformatter that wants to use as much horizontal space as possible? hell nope...

> Once they come up with an actually convincing new feature and still keep banning single quotes we might do a new fork (if no other more prominent institution or person (like Raymond Hettinger) does....
> Agreed?

sounds good!

**Comment by axgkl** [comment]
Done & closing. Thanks for the enlightenment.
